### ISSUE TITLE
Do your first movies in VisIt

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/summer-projects#10]
- [x] Wendy
- [x] Joshua

Hint: Use `wave.visit` example dataset and have a look at our [movie docs](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/using_visit/Animation/index.html)

**Comment by markcmiller86** [comment]
Apologies but I sent you to the wrong part of our docs to make a simple movie. You want to read [this part](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/using_visit/SavingPrinting/Saving_movies.html?highlight=movie) of the docs to make a simple movie. Similar to what I am uploading below.

The goal is to give you a frame of ref. for what aspects of movie making and animation VisIt can handle vs. what we need to delegate to a downstream 3rd party tool. This case I've given you is the *simplest* way to make a movie in VisIt. But, its also highly restrictive in what kind of *features* you can support. The next level up from this is [keyframing](https://youtu.be/tLm_3Vl9rLg) which is [documented in the animation section of our docs](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/using_visit/Animation/Keyframing.html)


https://user-images.githubusercontent.com/5720676/172493756-2f25eca8-697b-434e-91dd-e796bdcadb2b.mp4

**Comment by markcmiller86** [comment]
And, the next level up from KeyFraming animation is Python scripting where you write a looping python script that tells VisIt what specific things to do to produce each individual (static) image in a sequence of images that will get strung together into a movie. I think it makes sense for you to experience all 3 of these ways of movie making in order to have a better feel for what to keep within VisIt's perview and what to delegate downstream. That said, if we are satisifed with *just* simple movies, then I think we can declare victory on this task.


Once each of you has finished a *simple* movie similar to the one I uploaded here, please upload it here too. You want to create a `.mp4` file.

**Comment by corvette20** [comment]
Uploading movie (Josh).mp4…

**Comment by markcmiller86** [comment]
@corvette20 it doesn't look like it successfully uploaded your movie.

**Comment by corvette20** [comment]
@markcmiller86 that is weird. I will try downloading it again. Let me know if it works now please. I dragged the video and also dropped it into the editor. 


https://user-images.githubusercontent.com/19843453/172603340-b5dd179c-e7dd-4f7c-93f7-9d76a69dd369.mp4

**Comment by markcmiller86** [comment]
Hmm....I see you've made a 2nd attempt. Is it showing and playable for you here? It seems broken for me. How big is the file? If under 10 mb, maybe try emailing it to me. Or follow [the steps here](https://visit-dav.github.io/largedata/help/using-for-uploads.html) to upload it to our ftp site. Or, upload it to our shared google folder (which link I won't provide here but will email you).

**Comment by Magicat-0** [comment]
[keyframe demo movie wendy - Copy.zip](https://github.com/visit-dav/summer-projects/files/8865296/keyframe.demo.movie.wendy.-.Copy.zip)

**Comment by markcmiller86** [comment]
> keyframe demo movie wendy - Copy.zip

That worked. Thanks! As an aside...it would have worked simply by adding `.zip` to the end of the filename and attaching it and then letting me know (😉 ) that its NOT REALLY a zip file. GitHub just keys of the file's extension.

Your upload to Google folder also worked...which I then converted to `.mov` format and attached *natively* here so we can view it in line...

https://user-images.githubusercontent.com/5720676/172726268-9027394f-a2fe-4c58-a259-c959d6b5d3fd.mov

Great work. I am impressed 💪🏻! You did a key-frame animation which is a step up from the *simple* movie. That isn't easy to do. And, I am noticing some bugs in VisIt by viewing the result. The font size for your username in the lower-right corner keeps oscliatting in size. It also seems like the mpeg compression got pretty bad mid-way through the animation. But, great work getting that done.

@corvette20 all we're waiting on to close this issue is a valid upload of your movie either here as an attachment (the above appears broken) or to the google drive or just email it to me (if its small enough).

**Comment by markcmiller86** [comment]
BTW... @Magicat-0 and @corvette20 if you are so inclined, would you mind sharing your thoughts on your top 2 or 3 things about how absolutely wonderfuly or mind-numbingly challenging you found the movie making controls (either key framing or simple save movie) in VisIt to be to produce that movie? We value having perspectives from newbies you aren't too biased from having worked in this space and grown accustomed to and just accept all the useability issues 😉

**Comment by Magicat-0** [comment]
@markcmiller86 It was very easy following your youtube tutorial and user manual you linked above. 

The movie controls were easy to use (at least with the little i used it when making the key-frame animation). It kind of reminded me of dj/music software like fruity loops.
Compared to Maya and Blender, much more streamlined and simple without sacrificing results or having to add too many things to animate the object. I feel like doing the same thing in Maya would take ages.
I liked that you can have different windows opened and interact with them without having to close the previous ones.
Selecting something (plot, operator, etc) actually selects/applies it, if that makes sense? I.e. In other software sometimes it doesn't do anything or does something completely crazy or you have to add all these other modifiers so that it works.

Maybe as i use it more i can provide more useful input 😅

**Comment by corvette20** [comment]
@markcmiller86 
    I have attached I sent you my video file both over email and attached it in the google drive.

I thought the movie tutorial was really good. In the beginning, I did struggle a little bit with being able to locate the wave files. I think maybe you move the files closer to the new tutorials or place a hyperlink in there. Would be helpful for people that are not quite sure how to use the animation or movie function.
I think though overall it was pretty straightforward!

**Comment by markcmiller86** [comment]
Ok, converted @corvette20 `.mpeg` movie and uploaded to view inline here.

Thanks both. Great start for this week!

https://user-images.githubusercontent.com/5720676/172910817-29f29e3c-e56f-4816-8a92-b25ec2271af9.mov
