### ISSUE TITLE
Look into availability of windows virtual machines

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/summer-projects#11]

**Comment by markcmiller86** [comment]
@brugger1, @biagas or @cyrush any ideas on if/how we can make a Windows virtual machine available to summer interns?

**Comment by brugger1** [comment]
I don't know, but Nicole Armbruster sets up our new employees with virtual windows machines when they start, so I expect she could at least point you in the right direction. I would contact her.

**Comment by markcmiller86** [comment]
@corvette20 and @Magicat-0 it looks like the Amazon Virtual Desktop thing our LivIT dept set up for you could be the ticket here. I just looked [here](https://clients.amazonworkspaces.com) and I see that it provides a remote Windows env. for you on any kind of system.

The next fundamental question is whether you can copy and use the microCT software that came with the data there too? You might not be able to. It might have some licensing restriction that prevents it. But, please give it a try so we can decide if this is a useful means to utilize that software for the both of you.

I am unassinging myself here and we'll leave this unassigned in the "to do" list for now.

**Comment by Magicat-0** [comment]
> The next fundamental question is whether you can copy and use the microCT software that came with the data there too? You might not be able to. It might have some licensing restriction that prevents it. But, please give it a try so we can decide if this is a useful means to utilize that software for the both of you.

I downloaded the CTan to my AWS but was unable to install/run it. I got a message saying i needed admin rights so i tried running it as admin and got another error message saying this issue required ascension.
<img src="https://c.tenor.com/dXsMbRkpCHYAAAAd/ascension-sponge-bob.gif" width="150">

**Comment by corvette20** [comment]
@Magicat-0  I will try it on AWS before our meeting to see if I can run the microCT software too.

**Comment by markcmiller86** [comment]
I think we've concluded the AWS machines are not that helpful for our cause there.
