### ISSUE TITLE
Run VisIt in parallel to experience that

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/summer-projects#12]
- [ ] Wendy
- [x] Joshua

Use `mutli_ucd3d.silo` (it is a mult-block dataset) and produce **Mesh** plot, combined with **Pseudocolor** plot of any variable. Open up the **Compute Engines** dialog and watch what its doing in parallel. How many parallel tasks is it running?

**Comment by corvette20** [comment]
Mark, I have ran parallel starting the with the (np 4) but I am not quite sure how to check what is going on in parallel in the Compute Engine window. All I see in the window is processors not sure how to see parallel processes in the window.

**Comment by markcmiller86** [comment]
Is this locally on your macOS system or remotely on LLNL CZ systems?

To confirm, go to **File**`->**Compute engines...** and see what it shows as the **Processors** count as in below...

![Screen Shot 2022-06-15 at 1 44 34 PM](https://user-images.githubusercontent.com/5720676/173923852-21dfbdcd-f4f8-41dd-8aca-4cd55b9fe671.png)

![Screen Shot 2022-06-15 at 1 45 06 PM](https://user-images.githubusercontent.com/5720676/173923889-0a9eb0aa-5012-4041-9d8d-854abac9850a.png)

**Comment by corvette20** [comment]
Mark, 

I did all that just wanted to make sure that I was not missing anything.

Thank you!!

**Comment by corvette20** [comment]
I used 4 processors and made that all work.

**Comment by Magicat-0** [comment]
Mine was 8
