### ISSUE TITLE
Volumetric data analysis tool assessement

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/summer-projects#18]
Use criteria (preliminary, below) to evaluate 3-4 volumetric data analysis tools such as Slicer, CTAn (tool that was packaged with Prof Mondy's microCT data), TurtleSeg??, Inversuis??

* data size handling on 3 different dataset sizes (small < 100Mb, medium < 1GB, large > 50GB)
   * First, does it handle data from all these sizes?
   * Time how long key (TBD) operations take (some that come to mind below...not exhaustive...if you have other ideas, please investigate them)
      * produce a 3D model (stl) file
      * applying various filters (aniso-tropic smoothing might be a good one to test if available)
      * subset the volume into some number of pieces (if possible)
      * convert formats (maybe dicom to brick of value (bov) or something else)
* robustness of tool (does it crash often)
* useability (how easy was it to figure out how to do things from GUI alone)
* numerical (as opposed to visual) capabilities (measure things, pick values, compute things like averages or volumes, etc.)
* quality (how good visually or numerical
* List of supported data format(s) of input(s) and output(s)
* Does it require a lot of human babysitting?
* is there a programmatic (scripting) interface?
* availablility on Windows, macOS, Linux variants (Ubuntu, RedHat,
* open source or commercially licensed?
* does it take advantage of parallel resources (multi-core, GPU)?
* Any other unique features (relevant to our summer plans) or things to note

Do all your comparisons on the same platform (e.g. your windows laptop). Spend as much as one full day answering the above questions for each tool. Use the same criteria to evaluate each tool. Collect your results as [GFM markdown](https://gist.github.com/stevenyap/7038119) notes here in this issue using the following template

* Tool name
   * Assessment platform
      * Operating system name/version
      * CPU designation
      * GPU designation (if any)
      * Amount of main memory
      * Free disk space on the "system" drive
   * Data handling?
      * [ ] small
      * [ ] medium
      * [ ] large
   * Operations timings
      operation | small | med | large
      ---: | :---: | :---:| :---:
      op1
      op2
      op3
   * robustness (poor/average/superlative)
   * useability (poor/average/superlative)
   * numerical analysis features (list them here)
      * feature 1
      * feature 2
      * 
   * quality (poor/average/superlative)
   * list of supported formats and notes
      * dicom
      * tiff
      * png
      * STL (binary)
      * STL (ascii)
      * other format 1
      * other format 2
 * Much babysitting needed?
 * Programming interface?
 * Open source or commercially licensed?
 * Can it use parallel resources and if so how (multi-core, GPU, ...)
 * Platform availability
    * [ ] macOS
    * [ ] Windows
    * [ ] Ubuntu
    * [ ] RedHat
    * [ ] Centos
    * [ ] Build from sources
 * Other uniqe features
    * feature 1
    * feature 2
 * Ranking among those you've assessed

**Comment by markcmiller86** [comment]
@Magicat-0 I can't seem to find you assessement notes. Can you pls attach here?

**Comment by Magicat-0** [comment]
Here is the final (not very aesthetically pleasing) draft:

[Image analysis tool final draft.pdf](https://github.com/visit-dav/summer-projects/files/9183145/Image.analysis.tool.final.draft.pdf)
