### ISSUE TITLE
3D modeling and animation tool assessement

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/summer-projects#20]
Use criteria (preliminary, below) to evaluate 3-4 3D modeling and animation such as Blender, AfterEffects, Omniverse, Maya (as availability allows)

* data size handling on 3 different dataset sizes (small < 100Mb, medium < 1GB, large > 50GB)
   * First, does it handle data from all these sizes?
   * Time how long key (TBD) operations take (some that come to mind below...not exhaustive...if you have other ideas, please investigate them)
      * from first opening a 3D stl file to first view
      * applying various operators
      * subset the model into some number of pieces (if possible)
      * convert formats (maybe dicom to brick of value (bov) or something else)
* robustness of tool (does it crash often)
* useability (how easy was it to figure out how to do things from GUI alone)
* quality (how good visually or numerically)
* List of supported data format(s) of input(s) and output(s)
* How much human babysitting does the tool require to do its job(s) well?
* is there a programmatic (scripting) interface?
* availablility on Windows, macOS, Linux variants (Ubuntu, RedHat,
* open source or commercially licensed?
* does it take advantage of parallel resources (multi-core, GPU)?
* Any other unique features (relevant to our summer plans) or things to note

Do all your comparisons on the same platform (e.g. your windows laptop). Spend as much as one full day answering the above questions for each tool. Use the same criteria to evaluate each tool. Collect your results as [GFM markdown](https://gist.github.com/stevenyap/7038119) notes here in this issue using the following template

* Tool name
   * Assessment platform
      * Operating system name/version
      * CPU designation
      * GPU designation (if any)
      * Amount of main memory
      * Free disk space on the "system" drive
   * Data handling?
      * [ ] small
      * [ ] medium
      * [ ] large
   * Operations timings
      operation | small | med | large
      ---: | :---: | :---:| :---:
      op1
      op2
      op3
   * robustness (poor/average/superlative)
   * useability (poor/average/superlative)
   * quality (poor/average/superlative)
   * list of supported formats and notes
      * STL (binary)
      * STL (ascii)
      * USD
      * other format 1
      * other format 2
 * Much babysitting?
 * Programming interface?
 * Open source or commercially licensed?
 * Can it use parallel resources and if so how (multi-core, GPU, ...)
 * Platform availability
    * [ ] macOS
    * [ ] Windows
    * [ ] Ubuntu
    * [ ] RedHat
    * [ ] Centos
    * [ ] Build from sources
 * Other uniqe features
    * feature 1
    * feature 2
 * Ranking among those you've assessed

**Comment by corvette20** [comment]
Top 3
1. Blender
2. Houdini FX
3. Modo

**Comment by corvette20** [comment]
[3D Modeling .pdf](https://github.com/visit-dav/summer-projects/files/9028865/3D.Modeling.pdf)

**Comment by markcmiller86** [comment]
@corvette20 thanks for this. I have some quick questions about your assessement data though...

In the PDF, you indicate Maya ranked #5. Typo? Why is some of the text highlighted red? Can you remove that? Were you unable to do any operations timings whatsoever? Time to read? Time to first render from hitting the "go" button, etc.? Could you include some screen shots of each looking at the same dataset? Where you indicate parallelism is supported, can you elaborate how it is supported, to what scales in terms of core counts or threads? Did you have opinions regarding robustness of tools and/or how much babysitting they might require to get decent results out?

**Comment by markcmiller86** [comment]
@corvette20 did you have time to address any of the queries above? If so, please record your thoughts here.

**Comment by corvette20** [comment]
[3D Modeling (1).pdf](https://github.com/visit-dav/summer-projects/files/9169826/3D.Modeling.1.pdf)

This should answer your questions Mark
