### ISSUE TITLE
Outline for the next 5 weeks 

### ISSUE THREAD

**Issue by corvette20** [visit-dav/summer-projects#26]
Please attach your outline for the next five weeks of the program. Allowing Mark to see if we have thought of everything that needs to be completed. 

- [ ] Joshua 
- [ ] Wendy

**Comment by corvette20** [comment]
[outline for the next five weeks .pdf](https://github.com/visit-dav/summer-projects/files/9064470/outline.for.the.next.five.weeks.pdf)

**Comment by markcmiller86** [comment]
@corvette20 I think your outline looks fine. Only challenge is whether the datasets we actually have in hand have any landmarks in common. Just the toes alone do not normally physically connect to *each other* (at the blood vessel network level anyways). They each connect to the larger body of the foot which it isn't clear we have any data for (at any resolution). So, this question needs to be answered asap as it is kinda sorta fundamental to the whole plan.

Next, what do you do if you don't have common landmarks? What is your plan B? Some ideas...

* Find a whole foot blood vessel dataset on line and perform the same operations by first pre-segmenting it into toes and foot body and then attempt to re-align them using the same processes.
* Find a whole foot blood vessel dataset on line and use the foot-minus-toes part of that dataset as the *body* into which to try to fuse the microCT toes we have. If larger blood vessel orientation and position is highly similar from one person's foot to the next, we could potentially use the larger blood vessels to identify common landmarks to drive the fusion.
* Just orient the toe datasets we have relative to each other spatially based on a) our understanding of their size and shape in the microCT data we have and b) any common/standard toe/foot geometries we can find online. We aren't using physical landmarks in the data at that point but many of the operations are highly similar.

**Comment by corvette20** [comment]
The plan has been adjusted after @markcmiller86 and I have spoken! I have the plan and am in the middle of executing it.
