### ISSUE TITLE
Data on Big Toe / Right foot (week 2 updates) (Joshua's project)

### ISSUE THREAD

**Issue by corvette20** [visit-dav/summer-projects#27]
I looked at a few different samples. 

- 4x4x4 data 

![Screen Shot 2022-07-18 at 11 27 51 AM](https://user-images.githubusercontent.com/19843453/179617649-42b1ad5a-dcc5-4db5-bab4-a24674f66f52.png)
![Screen Shot 2022-07-18 at 11 27 04 AM](https://user-images.githubusercontent.com/19843453/179617674-1b8b4d5e-61f3-403f-ab23-5a357ed199c9.png)

From the data, I found that the middle of the data is (8x10^3)

- Right foot (CT data)

![Screen Shot 2022-07-18 at 1 59 04 PM](https://user-images.githubusercontent.com/19843453/179618012-0357970e-2eec-4dc4-866c-1e9bc3d4a626.png)
![Screen Shot 2022-07-18 at 1 58 01 PM](https://user-images.githubusercontent.com/19843453/179618094-ebed853d-18b5-4cfe-a7f2-ae4eb69c4b04.png)

From the data, I found that the middle of the data is (8x10^3)

- Big Toe (Micro CT data)

![Screen Shot 2022-07-18 at 4 54 34 PM](https://user-images.githubusercontent.com/19843453/179618315-5e2eef48-f0e5-4287-8a81-d463dd52be2e.png)
![Screen Shot 2022-07-18 at 4 50 39 PM](https://user-images.githubusercontent.com/19843453/179618332-605cca61-4932-47bb-9cab-7970f8996b3e.png)

From the data, I found that the middle of the data is (.6x10^3)

**Comment by markcmiller86** [comment]
@corvette20 ok, thanks for this. Did you do this analysis for a few of the larger, easily identified vessels? Its probably ok if you didn't but having a few different examples is good just to be sure we don't have a dataset with wildly different outside-to-inside density profiles. I don't think we do but its always good to double check.

I think you inadvertently mixed up the two thresholds.

To summarize your results...
* Low-res, whole foot data: you propose a threshold of 0.6x10<sup>3</sup> (600) 
* High-res, individual toe data, you propose a threshold of 8x10<sup>3</sup> (8000)

I agree with this.

Now, on to identifying 4 landmarks you can find in common between the the lo-res, whole foot and the hi-res big toe. You want these landmarks to be somewhat *distributed* from each each other. This helps to minimize possible linear dependencies that would make the process of calculating the transform parameters more sensitive to minor variations in their values.

**Our goal** is a transform that maps **FROM** the hi-res toe data (we'll do it for each toe but just the big toe is fine for now), **TO** its proper position in the lo-res whole foot data. So, the **target** coordinate system is that of the lo-res whole foot. Now, these datasets are different in many ways. We know their scales are different. The big toe is 4032x4032x9000 (or there abouts) while the lo-res whole foot is 512x512x300 (about). There will also be *translation* and maybe *rotation*. Oh, almost forgot...there is a diffference in the oritentation of slices (.tiff images) to the XYZ coordiantes. In lo-res whole foot, heel-to-toe oriention is along X axis. In hi-res big toe, it is in Z.

See [this article](https://towardsdatascience.com/find-linear-transformation-based-on-known-points-64785e987db0) for a 2D example.

You want 3D though. See [this article](https://www.brainvoyager.com/bv/doc/UsersGuide/CoordsAndTransforms/SpatialTransformationMatrices.html) for more details that work for 3D.

Using that article...you will have the equation **y** = **Mx** for every *pair* of landmark points you identify where **y** is a point in the target (lo-res whole foot) and **x** is a point in the source (hi-res toe). The **M** matrix is 4x4 so it has 16 entries but the 3D article above explains why there are zeros in **M** on the bottom row and last column. So, there are really only 12 unknowns. Each *pair* of points defines 3 equations so 4 pairs of landmark points defines 12 equations and with that you have a problem in 12 equations and 12 unknowns to define the **M** transform. If you want, you can go for more landmark points creating N equations in 12 unknowns and then you can solve the *least squares* solutions of that over-determined system to get the **M** matrix. It is those values you would enter into VisIt's transform operator to map the toe onto the foot.

If we just map the toe onto the foot, we have a problem in that where the two overlap, we have overlapping data. We don't want that. So, we also need to clip away or other wise cut out the lo-res whole foot data for the region we are mapping the toe into. I think the box operator in VisIt is what you want to use for that. What are the parameters for that box? They are the same as the extreme corners of the big-toe mapped through the transform, **M**.

**Comment by markcmiller86** [comment]
Once you have the above designed, we then need to build a *keyframe* sequence that will serve as the basis for the animation. Let me propose a sequence and see what you think...

1. Start with simple Pseudocolor plot of whole brick of lo-res whole foot data, maybe rotate around it for a bit.
2. Then, make the "air" part of the dataset (low density stuff) slowly melt away revealing the blood vessel network alone.
3. Again, rotate it around a bit.
4. Then apply the box operator to the big toe in such a way that over a few secs of animation the toe is cut away...the box operator would slowly grow (in X direction  I think for lo-res whole foot dataset). 
5. Oh...what could be way cool is that you zoom in on the big toe and have the box operator on the one hand remove the lo-res data but have another box operator reveal the high res data right behind it. So, it would be like a sweep over the big toe where the lo-res (in front of the sweep) is removed and the hi-res (behind the sweep) is revealed.

I know we talked about maybe animating the *transformation* itself so that the hi-res big toe appeared to *fly into place* from some position away from the lo-res whole foot. That is also doable but I think the above animation might be cooler.

**Comment by wmondy** [comment]
What are the units for the distance measurements here?

**Comment by markcmiller86** [comment]
> What are the units for the distance measurements here?

@corvette20 can you reply? I think the folders contining the `.tiff` slice images contain some readme files or other such metadata with that information.

**Comment by markcmiller86** [comment]
@corvette20 I tried some volume rendering in VisIt...

[short video](https://youtu.be/RCPGm-5YgOE)

![Screen Shot 2022-07-21 at 8 45 53 PM](https://user-images.githubusercontent.com/5720676/180358314-c6d377ec-c891-45cd-b8ec-68342e4a3846.png)

[session file](https://github.com/visit-dav/summer-projects/files/9164452/foo.session.gz)

It helps to orient yourself in the data but you can't pick on a volume plot.

**Comment by corvette20** [comment]
Thank you for the video!
