### ISSUE TITLE
Rendering CT data

### ISSUE THREAD

**Issue by corvette20** [visit-dav/summer-projects#29]
As we talked about on Friday, I was tasked to try to verify to see if the CT data had different data or better rendering in the goal to render the big toe. I verified my results with Mark yesterday.

right_foot_512x589x503 (COR_0010) 
Seems as though the information being shown is not relevant to the big or the foot (insight needed)
![Screen Shot 2022-07-26 at 1 19 31 PM](https://user-images.githubusercontent.com/19843453/181247377-4ad7fb28-19b3-4ec7-a655-884331912110.png)

RIGHT_FOOT_788x512x502 (SAG_0008)
file does not seem to have anything information
![Screen Shot 2022-07-26 at 3 20 47 PM](https://user-images.githubusercontent.com/19843453/181247637-e771c0f5-b559-461c-b0ef-711d5bf4253d.png)

right_foot_UR70_3_0004_512x512x326 (UR70_3_0004)
One of the sets that has big toe information
![Screen Shot 2022-07-26 at 7 03 51 PM](https://user-images.githubusercontent.com/19843453/181247917-f620e28f-340e-487a-9d44-c7b3c53175a8.png)

right_foot_UR70_3_0007_512x512x326 (UR70_3_0007)
One of the sets that have big toe information
![Screen Shot 2022-07-26 at 7 19 28 PM](https://user-images.githubusercontent.com/19843453/181248314-2d0eede3-d391-4c95-b4de-15bfdb74ab51.png)

RIGHT_FOOT_788x512x170 (SAG_0006)
The file seems to not be in the correct order
![Screen Shot 2022-07-26 at 7 51 02 PM](https://user-images.githubusercontent.com/19843453/181248657-847c3140-2cf2-4dc4-a83e-bb9a50549599.png)

right_foot_UR70_3_0005_512x512x538
The file has information that looks like the whole foot from a different angle 
![Screen Shot 2022-07-27 at 10 14 20 AM](https://user-images.githubusercontent.com/19843453/181286498-0c327974-eac4-4d10-9f40-4efb5f4278fd.png)

RIGHT_FOOT_788x512x170
No information in file 
![Screen Shot 2022-07-27 at 10 22 56 AM](https://user-images.githubusercontent.com/19843453/181286559-ccd274f6-5bee-479c-a31f-5330bd37209b.png)

Some of these pictures have no data or seem like the ordering of the slices could be wrong. If we could get some insight on this information to help me edit the picture or pull out more data, it would be greatly appreciated.

**Comment by markcmiller86** [comment]
@wmondy might you have any insights here?

**Comment by markcmiller86** [comment]
Thanks for the quick analysis @corvette20!

My recollection is also that when we rotated those that looked jumbled, there was no view that suggested it was just the first few slices that were bad. Its jumbled all over the whole volume.

**Comment by markcmiller86** [comment]
I think we can declare this done. We've taken a look at all the other datasets and haven't found anything more promising than what we were working with earlier.

**Comment by wmondy2** [comment]
Sorry just seeing this. 

If you recall from our lasts discussion regarding these data sets some of the data sets were captured with x-ray beam at higher voltage, 120kv vs 85kv. Those Captured it at a higher voltage may have a fainter image because of the X-ray beam passing more readily through the vascular corrosion cast material.  If you want to see it you it will have to try using a lower threshold intensity levels to pull out the 3D image.  

But the models we have now maybe just fine as Mark you indicated.

Thanks for the reconstructions!

**Comment by markcmiller86** [comment]
@wmondy2 changing thresholds would change *whether* we pull out vessels or not but it would not change the jumbled nature of the results. We tried various thresholds when analyzing `SAG_0008` and `SAG_0006` files. I don't think we understand the structure of these file sets.

**Comment by markcmiller86** [comment]
@corvette20 I was able to get the issues you saw here corrected by reconverting the files to 16bit gray scale.

**Comment by wmondy2** [comment]
You were very smart in figuring out the issue, thank you Mark.
