### ISSUE TITLE
3 Nodes Picked on Model 

### ISSUE THREAD

**Issue by corvette20** [visit-dav/summer-projects#31]
Here is a combination of my update along with what I have worked on today. @markcmiller86, I tried bringing in both the big toe and the foot into the same Visit window but I realized that I could not use the box function. I believe this is because the box function for both the big toe and the foot are different sizes. If you have any hints on how to bring both in let me know, please.

Node Pick from UR70_3_0007

- Pick 1 (x,y,z) (168,259,279)  Contour (400)
![Screen Shot 2022-07-19 at 6 01 39 PM](https://user-images.githubusercontent.com/19843453/182282423-2561aa5e-6ba7-43f9-9e74-a8520a1c5a31.png)

- Pick 2 (x,y,z) (125,262,246)  Contour (400)
![Screen Shot 2022-07-29 at 10 41 00 AM](https://user-images.githubusercontent.com/19843453/182282861-0d3dcc1c-39da-486b-a514-56f77023d697.PNG)
![Screen Shot 2022-07-29 at 10 34 06 AM 2](https://user-images.githubusercontent.com/19843453/182282989-a076c18c-7875-4a4e-8d52-26a359519101.PNG)

- Pick 3 (x,y,z) (160,253,274)  Contour (400)
![Screen Shot 2022-08-01 at 2 14 18 PM](https://user-images.githubusercontent.com/19843453/182284139-67f7feea-3d33-44c2-b657-0d1e753e4a21.PNG)
![Screen Shot 2022-08-01 at 2 16 19 PM](https://user-images.githubusercontent.com/19843453/182284163-906fa28c-af6a-46c0-9eb5-dde497aed780.PNG)
![Screen Shot 2022-08-01 at 4 52 19 PM](https://user-images.githubusercontent.com/19843453/182284224-16540c2a-e8ff-457b-af4c-149343ce64f2.PNG)

![Screen Shot 2022-08-01 at 5 08 06 PM](https://user-images.githubusercontent.com/19843453/182281561-c18436e3-5355-4b15-8b78-e78a5fe8faf0.PNG)

Node Pick from 4x4x4 downsample

- Pick 1 (x,y,z) (844,599,623) Contour (17000)
![Screen Shot 2022-07-19 at 1 19 48 PM](https://user-images.githubusercontent.com/19843453/182282570-af6cae28-26bd-4a42-80fa-2d06ccb2d4a7.png)

- Pick 2 (x,y,z) (698,626,1263) Contour (17000)
![Screen Shot 2022-07-28 at 10 46 15 AM](https://user-images.githubusercontent.com/19843453/182282685-2b8ad9cc-4ea2-45e8-9c9c-ca06634070f6.png)
![Screen Shot 2022-07-28 at 10 44 51 AM](https://user-images.githubusercontent.com/19843453/182282746-30a83d9c-1b61-4d71-b971-181ce621625d.png)

- Pick 3 (x,y,z) (680,390,824) Contour (17000)
![Screen Shot 2022-08-01 at 12 36 04 PM](https://user-images.githubusercontent.com/19843453/182283699-861b4bfb-a103-41c6-8a14-6971cf020982.PNG)
![Screen Shot 2022-08-01 at 12 48 00 PM](https://user-images.githubusercontent.com/19843453/182283799-a0f5baac-78c7-49aa-823f-8186f6780ed6.PNG)
![Screen Shot 2022-08-01 at 12 49 02 PM](https://user-images.githubusercontent.com/19843453/182283840-5f5e85ad-dd7f-4ce3-8db0-64fcefc2821c.PNG)

![Screen Shot 2022-08-01 at 5 24 07 PM 2](https://user-images.githubusercontent.com/19843453/182284786-20bb856e-89a7-41c1-839e-8a38b9af1001.PNG)

All the points chosen are well documented and have many connection points to assure they match high and low res data.

**Comment by corvette20** [comment]
The next steps are to work on testing the displacements that were solved from the three picks from high and low res.

**Comment by markcmiller86** [comment]
@corvette20 at first look these like **GREAT**! So, from these, do you have the point's coordinates in both the low-res and high-res data sets? If so, can you r ecord them here?

You have a choice of node-pick or zone-pick in VisIt to do the picks. Which will you (or did you) use? Can you perhaps comment on which might be *better*?

**Comment by corvette20** [comment]
@markcmiller86 thanks for taking a look. Yes, I know the way that GitHub lays out the data kind of looks weird but the Nodal picks that I chose are actually above each set of pictures! Which is I have posted the high and low res picks laid out 


Node Pick from UR70_3_0007
- Pick 1 (x,y,z) (168,259,279)  Contour (400)
- Pick 2 (x,y,z) (125,262,246)  Contour (400)
- Pick 3 (x,y,z) (160,253,274)  Contour (400)
- Pick 4 (x,y,z) (102,262,265) Contour (400)

Node Pick from 4x4x4 downsample
- Pick 1 (x,y,z) (844,599,623) Contour (17000)
- Pick 2 (x,y,z) (698,626,1263) Contour (17000)
- Pick 3 (x,y,z) (680,390,824) Contour (17000)
- Pick 4 (x,y,z) (648,507,1701) Contour (17000)

**Comment by markcmiller86** [comment]
@corvette20 once you've decided the 4th landmark, here are the equations...

![Screen Shot 2022-08-04 at 7 23 18 AM](https://user-images.githubusercontent.com/5720676/182871240-456f9f8a-5348-4f7a-bbdb-25c84fce4390.png)
![Screen Shot 2022-08-02 at 6 57 25 PM](https://user-images.githubusercontent.com/5720676/182507749-4a835052-f12e-4aa2-bb6d-a958da341eea.png)

You would write down the above equations for each pair of points. I've designed the notation to match the form used in [this tool](https://www.math.odu.edu/~bogacki/cgi-bin/lat.cgi?c=sys). So, you would plug all the coefficients of the x's into the rows of that system of equations and hit the submit button. It should then give you all the x's. Those are the numbers we would enter into the `Linear` tab of VisIt's transform operator.

Lemme know if this doesn't make sense.

**Comment by markcmiller86** [comment]
Not also that this will do the *opposite* of what we were trying to do manually today by eye-balling it. Today, I was trying to transform the low-res data *onto* the high-res data. But, what we really want is the opposite of that...to transform the high-res toe onto the low-res whole foot so that we can effectively fuse them replacing the low-res toe portion with our high res toe.

**Comment by corvette20** [comment]
Finally able to find the last point that makes the most sense and is far away enough from the other points:

Node Pick from UR70_3_0007

Pick 4 (x,y,z) (102,262,265) Contour (400)
![Screen Shot 2022-08-04 at 1 03 32 PM](https://user-images.githubusercontent.com/19843453/182916723-2b4f50ea-197e-4f1b-83a2-4344760c6ff3.png)
![Screen Shot 2022-08-04 at 1 04 36 PM](https://user-images.githubusercontent.com/19843453/182916751-b66f40ad-9ecb-47f6-8d3d-d5d63bf37952.png)
![Screen Shot 2022-08-04 at 12 35 58 PM](https://user-images.githubusercontent.com/19843453/182917027-3fc4a83b-2001-438d-9aa3-5e62edf50563.png)


Node Pick from 4x4x4 downsample

Pick 4 (x,y,z) (648,507,1701) Contour (17000
![Screen Shot 2022-08-04 at 1 05 43 PM](https://user-images.githubusercontent.com/19843453/182916784-314a14aa-db21-46d8-8bbc-29753b9ddd09.png)
![Screen Shot 2022-08-04 at 1 08 46 PM](https://user-images.githubusercontent.com/19843453/182916872-8678af69-395c-4572-b415-142688cb7144.png)
![Screen Shot 2022-08-04 at 1 10 04 PM](https://user-images.githubusercontent.com/19843453/182916933-368bb700-1879-4268-a2d0-d8573375a4f0.png)

**Comment by markcmiller86** [comment]
Ok, that is great news @corvette20. Now, do the remaining steps I outlined with the math above make sense?

**Comment by corvette20** [comment]
@markcmiller86, the math makes sense!

It is a very long problem to be honest though
 
[LLNL 12x12.pdf](https://github.com/visit-dav/summer-projects/files/9270133/LLNL.12x12.pdf)

**Comment by markcmiller86** [comment]
Ok, something looks off about the resulting system you attached. Lets take pair #1...

- **L** = Pick 1 (x,y,z) (168,259,279) Contour (400)
- **H** = Pick 1 (x,y,z) (844,599,623) Contour (17000)

We should have 

```
844x1 + 599x2 + 623x3 + x4 +  ...                                                       = 168
          ...              + 844x5 + 599x6 + 623x7 + x8 + ...                           = 259
          ...                           ...             + 855x9 + 599x10 + 623x11 + x12 = 279
```

Oh, wait, I see, its re-ordered the equations on first page of your pdf file.

Ok, I think this is right modulo one caveat....we haven't actually taken into account the actual spatial size of pixels in CT data and micro CT data nor the distance between slice-scans. Nonetheless, the transform should orient things correctly, even if the scale is bound to be off.

**Comment by markcmiller86** [comment]
It looks like its given all the coefficients as ratios of some large numbers. Lets work those divisions out to get the actual numbers. So, for example, for x<sub>11</sub>, I get 0.026427.

**Comment by markcmiller86** [comment]
> It is a very long problem to be honest though

BTW...not sure what you mean by this. Its 12 equations in 12 unknowns. That might have been large for a (human) computer of the 1950s but anyone's wrist watch can do that today. Thats why I went looking for and found an on-line solver that would just compute it for us 😉

**Comment by corvette20** [comment]
Mark, I worked out some of these by hand just because I love math!

**Comment by corvette20** [comment]
@markcmiller86, This morning I have been doing some things with the data that we input. I am realizing that something weird is happening.

The image that I transform with that liner matrix makes the object flat. I was wondering if you have any hints on how to make the image not flat anymore when I do the liner transformation! 
![Screen Shot 2022-08-05 at 12 35 35 PM](https://user-images.githubusercontent.com/19843453/183122887-bfaa7a2e-ddee-44d3-846c-530b5c3da67b.png)

**Comment by markcmiller86** [comment]
* I wonder if application of box operator may have effected pick outputs?
* In this image above, box operator is applied *only* to low res whole foot, correct?
* the caveat above about actual numerical differences in the spatial scale of pixels plays some roll

**Comment by corvette20** [comment]
I feel like picks should be relative to the whole image, not relative to the box.

In this case, I have a box operator on both the high and the low res data. Even if I used the cylinder operator would not that have a similar effect? 
![Screen Shot 2022-08-05 at 1 15 57 PM](https://user-images.githubusercontent.com/19843453/183128065-8e4a7472-5c42-4c30-817c-c962d7b8b9c7.png)

Yeah, I agree I do notice that a little but to be completely honest I have them almost lined up!

**Comment by markcmiller86** [comment]
> I feel like picks should be relative to the whole image, not relative to the box.

Sure. I *feel* the same way. But, that doesn't mean it is or that we know for sure. I would do a simple test just to be sure.

**Comment by corvette20** [comment]
@markcmiller86, I sent you the session files that I was looking at on Friday as a give function on the VNC!
