### ISSUE TITLE
Some Full Res Views

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/summer-projects#32]
I tried various things to remove the clyindrical mounting device from the scanned specimen of the big toe.

* cylinder clip operator
* cylinder expression + threshold
* box operator
* index-select operator
* various numbers of nodes (8, 16, 32) and processors (288...1172) on pascal and lassen
* 3.1.4 and 3.3.0 versions of VisIt

Eventually, VisIt would crash. I thought cause might be memory exhaustion. Not so sure. At 32 nodes and 1000+ processors, I thought the big toe data should be fine. However, all the operators I used did introduce an ~10x memory hit because the underlying mesh representation needs to change from structured to unstructured.

Each slice is 31mb (at 16bit per pixel. I dunno if VTK's image readers honor that or wind up reading it into 32-bit type which would then yeild another 2x memory hit). There are ~9000 slices for a total of 279 Gigabytes (or maybe twice that). Nodes on pascal and lassen are 256 Gigabytes. Now, there are intermediate copies of data that get created like triangles from iso-contour and normals for those and that can represent sizes on the order of orig. dataset (or more). But, I thought that 10 nodes should be sufficient for this data and either that is false or there are *several* bugs in various of the plots and operators I used.

Anyways, if I did not attempt to remove the cylindrical mounting bracket for the specimen, I did have more success with VisIt but we are limited in views of the data too because few views are possible without also seeing that mounting bracket and having it obscure the real data.

Below are a number of screen captures....

![Screen Shot 2022-08-06 at 3 17 25 PM](https://user-images.githubusercontent.com/5720676/183436153-b1bbf5ee-33c2-4ab8-ac94-d39432c5ff83.png)

![Screen Shot 2022-08-06 at 3 17 09 PM](https://user-images.githubusercontent.com/5720676/183436213-d6aec242-1430-4f8a-b6d6-c64482a3afe0.png)

![Screen Shot 2022-08-06 at 3 15 30 PM](https://user-images.githubusercontent.com/5720676/183436258-f09ef60f-83e8-471d-a1b1-f46d1af260d0.png)

![Screen Shot 2022-08-06 at 3 14 06 PM](https://user-images.githubusercontent.com/5720676/183436272-332593ac-9c15-4311-87c4-8a570957e1ae.png)

![Screen Shot 2022-08-06 at 3 13 21 PM](https://user-images.githubusercontent.com/5720676/183436281-0e03080c-e5e4-447f-92da-8a7ca102095f.png)

![Screen Shot 2022-08-06 at 3 13 02 PM](https://user-images.githubusercontent.com/5720676/183436299-20b8e6c2-0567-4f8f-ab8c-64464faf82b2.png)

**Comment by markcmiller86** [comment]
BTW, @wmondy SCEM scans show cotton fibers at ~10-20 um and I [this ref](https://journals.sagepub.com/doi/full/10.1177/15589250211024225) also mentiones that scale and I think I indeed do see some in these images...

This is a bit of a surprise since density to xray I assume is much different than specimen CC resin.

**Comment by markcmiller86** [comment]
There is some info in these refs about *resolution* of corrosion cast process itself...

* https://onlinelibrary.wiley.com/doi/full/10.1002/app.52284
* https://link.springer.com/chapter/10.1007/978-3-7091-9230-6_2

**Comment by wmondy** [comment]
Nice work Mark!!!  Thank you for doing this full res reconstruction - capturing and sharing these images.

**Comment by markcmiller86** [comment]
@wmondy one thing I would like to do soon is find a good color map that allows us to match these views with some of your SEM views. The red just doesn't work for that. Also, I think it might be worthwhile to try to *duplicate* some of the SEM images with volume rendering. We should talk about what is required to do that (in addition to color map). I think we need some idea of the electron beam attenuation properties into the material so that we can define equiv. *transfer* functions for volume rendering. Getting the same view angles would be great too.

**Comment by wmondy2** [comment]
The color scale is an old fashioned grey scale that you find on a old black and white TV.  The before CCD chips were invented and used to replace film, Electron microscopy images were first formed on a phosphorus screen then project on to the emulsion of B&W Film.  In the case of SEM a high quality Polaroid Instamatic film was used.  TEM used film plates of various sizes ie. 4"x3"depending on the scope manufacture.  

The for SEM the beam angle to the specimen surface was changed by tilting the stage on which the specimen was attached in order to get the best shot of an area of interest.
