### ISSUE TITLE
Transfer most recent microCT dataset to LLNL systems

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/summer-projects#8]

**Comment by markcmiller86** [comment]
OMG...you won't believe how much trouble I've made myself trying to download the `bigtoe.stl` 73 Gigabyte dataset Prof. Mondy uploaded to our shared google drive.

I tried `wget`, `curl`, and raw python `requests` module. I kept getting an error message saying too many users had attempted to download the file. That was a red herring though. The only way I was able to download it was via a web browser and that estimated 3+ days to complete the download!

I believe the browser-in-the-middle was causing the download to go very, very slowly. LLNL has good networks so it shouldn't take 3+ days to move 73 Gibabytes here.

Eventually, I found [this article](https://bytesbin.com/how-to-download-a-large-file-from-google-drive-quickly/) and had to take the Google OAuth approach. It is currently downloading to `/p/luster1/miller86` on `pascal`. It says it will take about 3.5 hours. Thats better than 3+ days!

It might have been better to download Goolge's python module tools and try it that way too.

Anyways...Its nice to have figured out how to move files to/from google drive.

**Comment by corvette20** [comment]
I have downloaded Hopper and am trying to connect to the LNLL supercomputer to complete the upload.

If you have a specific one that you would like me to upload it to please let me know.

I am having an issue uploading the file because on hopper they are asking me for the
Host:
Portal:
User:
Protocol: 
I have looked online not quite sure where to find this though.

**Comment by markcmiller86** [comment]
You will need to use /p/lustre1/Joshua or maybe /p/lustre2/Joshua



"corvette20" wrote:


I have downloaded Hopper and am trying to connect to the LNLL supercomputer to complete the upload.

If you have a specific one that you would like me to upload it to please let me know.

I am having an issue uploading the file because on hopper they are asking me for the
Host:
Portal:
User:
Protocol:
I have looked online not quite sure where to find this though.

**Comment by markcmiller86** [comment]
Sorry, host would be one of the LC systems I requested accounts on. Any remails regarding pascal, corona, quartz or lassen accounts?

I will go look at status of those requests.

**Comment by markcmiller86** [comment]
We will try to enlist help from @wmondy this weekend to see if we can make this transfer with his active accounts now that he has a token. So, I am unassigning @corvette20 for now and assigning to me

**Comment by markcmiller86** [comment]
@wmondy has shipped hard drive via UPS. I will upload on LLNL systems once I have it...probably Wed/Thu this week.

**Comment by markcmiller86** [comment]
Ok, we can declare victory here.

I would not have realized everything that was involved in getting such a large dataset transferred here. I ultimately had to enlist the help of a sys-admin who was able to use a special system to scan the usb drive for viruses in 3 hours.

I've put the files on LLNL CZ systems at `/p/lustre1/miller86/ctdata`. 

I am going to have to add a new issue to a) put everyone in the `visit` group and then b) `chgrp` all these files so that others can read it.

I did some brief integrity checks to confirm everything that was supposed to get copied made it...

1. On `thembisa.llnl.gov` (the machine I connected the USB drive to)...
   * `find CT_Datasets MicroCT_Datasets -name '*.tif' -exec ls -l {} \; > files_on_thembisa.txt`
   * The above produced a list of 62,908 files
   * The `ls -l` part of the command produces a *long* listing of each file which indicates total bytes of each file
2. I did the same command on `quartz.llnl.gov` and got the same number of files but listed in a different order
3. Those raw file lists are attached here...
   * [files_on_thembisa.txt.gz](https://github.com/visit-dav/summer-projects/files/8929440/files_on_thembisa.txt.gz)
   * [files_on_quartz.txt.gz](https://github.com/visit-dav/summer-projects/files/8929439/files_on_quartz.txt.gz)
4. After sorting and filtering out some garbage (e.g. dates of files) using these commands...
   * `cat files_on_thembisa.txt | sort -k 9 | cut -d' ' -f5,9 > mondy_orig.txt`
   * `cat files_on_quartz.txt | sort -k 9 | cut -d' ' -f5,9 > llnl_copy.txt`
   I get zero diffs in the file lists (which shows both names and sizes).

So, I think the copy is good.
